type TemperatureUnit = "K" | "R" | "°C" | "°F"
type TimeUnit = "s" | "min" | "h"
type MassUnit = "mg" | "g" | "kg" | "lb"
type MolarUnit = "mol" | "lbmol" | "kmol"
type VolumeUnit = "L" | "m^3" | "cm^3"
